Add support for scraping parental guide page
cinemagoer/cinemagoerng pull request #5
Opened 2024-07-01 20:20 UTC by mhdzumair

2024-07-02 05:10 UTC, mhdzumair commented
@uyar ready for review. Sorry for not able to push the changes sooner.

2024-07-02 19:16 UTC, uyar commented
Thanks a lot for your work. I'll get to it as soon as I can.

2024-07-02 19:55 UTC, uyar approved these changes

2024-07-02 19:58 UTC, uyar commented
Sorry, I've mistakenly approved all changes. I just meant the commit that fixes the bad plot parser, I've pulled in that one. I'll get to the others too.

2024-07-02 20:07 UTC, uyar requested changes
Style checks are failing. You can try with `ruff check --preview cinemagoerng tests`.

2024-07-02 20:09 UTC, uyar commented on cinemagoerng/model.py
The class name `Votes` can be confused with the movie votes. Maybe rename to something like `AdvisoryVotes`?

2024-07-02 20:11 UTC, uyar commented on tests/test_parentalguide.py
Could you add some more tests to cover other cases?

2024-07-02 20:16 UTC, uyar commented on cinemagoerng/specs/title_parental_guide.json
Indentation is inconsistent. We should stick to 2 spaces.

2024-07-04 10:34 UTC, mhdzumair commented on tests/test_parentalguide.py
updated

2024-07-04 10:36 UTC, uyar commented
Looks like you've run black on the code but I don't like black. It changed way too many files now that the PR has lost its focus and diverged from its purpose.

2024-07-04 11:33 UTC, mhdzumair commented on tests/test_parentalguide.py
Added more test data

2024-07-04 13:34 UTC, mhdzumair commented
> Looks like you've run black on the code but I don't like black. It changed way too many files now that the PR has lost its focus and diverged from its purpose.

I usually use black, however I'm not setting up black for this project, instead I ran this command, 
`ruff format cinemagoerng tests`   also updated the max line length to 119, if you want to revert it back the line length i can revert it and reformat it again.

2024-07-04 18:47 UTC, uyar commented
> I usually use black, however I'm not setting up black for this project, instead I ran this command, `ruff format cinemagoerng tests` also updated the max line length to 119, if you want to revert it back the line length i can revert it and reformat it again.

Though, AFAIK, rust-format is more configurable than black, I don't like autoformatters. Especially the line length issue. I believe that 79 characters is a good limit (except for tests) and if you have a good reason to break it, you can do so explicitly by using a `noqa: E501`.

The problem with the PR at the moment is that a lot of stuff have been bundled into one large changeset (like the title also indicates). If you have the time, could you divide these into smaller PRs for one thing each (parental guide, paginated akas, etc). I've already separated and merged the plot fix.

If you don't have the time or just don't want to do it, that's fine. I'll go over your changes and incorporate them one by one. But, for future reference, please keep your PRs focused to one thing at a time.

2024-07-05 01:57 UTC, mhdzumair commented
Sure will create a seperate PRs.

2024-07-05 01:57 UTC, closed without merging